### ISSUE TITLE
instantiate FrontendUser with objectManager

### ISSUE THREAD

**Issue by waldhacker1** [pixelant/pxa_newsletter_subscription#1]
Hi,

my merge request from
https://bitbucket.org/pixelant/pxa_newsletter_subscription/pull-requests/3/task-add-signalslot-after-fe_user-creation/diff
was merged a few months before.
Later, you merged it by hand (i think)
https://bitbucket.org/pixelant/pxa_newsletter_subscription/commits/5a996d8363702429796926f20a1f28dc857c36bb?at=master
As you can see, you forgot the object manager part

        $frontendUser = $this->objectManager->get(\Pixelant\PxaNewsletterSubscription\Domain\Model\FrontendUser::class);

It would be cool if you can rectify this, because i need to extend the extebase model which is not possible for now.

**Comment by MattiasNilsson** [comment]
@tritumRz We have now made a new release with fixes this issue: 

https://github.com/pixelant/pxa_newsletter_subscription/releases/tag/v4.0.2
