### ISSUE TITLE
Harden JS

### ISSUE THREAD

**Issue by olforestman** [pixelant/pxa_newsletter_subscription#3]
The issue described on [the old bitbucket repo](https://bitbucket.org/pixelant/pxa_newsletter_subscription/issues/7/harden-js) is still open. We will provide a PR since this should really be fixed.

**Comment by MattiasNilsson** [comment]
@tritumBj Thanks for taking care! 👍

**Comment by MattiasNilsson** [comment]
Solved with: https://github.com/pixelant/pxa_newsletter_subscription/pull/4
