### ISSUE TITLE
Ajax Error

### ISSUE THREAD

**Issue by topsnet-holgerd** [pixelant/pxa_newsletter_subscription#36]
I've got an error in typo3 log: Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1313855173: The controller "Ajax" is not allowed by plugin "Subscription". Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php. It's the current ext_localconf.php from version 10.0.0. On subscribing I get In the console of my browser:
Form.js?1592912073:122 POST https://www.example.de/index.html?tx_pxanewslettersubscription_subscription%5Baction%5D=subscribe&tx_pxanewslettersubscription_subscription%5Bcontroller%5D=Ajax&cHash=be2872029811e543e16eee8d75a0e5cf 500 (Internal Server Error)
_ajaxRequest @ Form.js?1592912073:122
(anonymous) @ Form.js?1592912073:30
Form.js?1592912073:92 Uncaught TypeError: Cannot read property 'errors' of null
    at XMLHttpRequest.<anonymous> (Form.js?1592912073:92)
(anonymous) @  #Form.js?1592912073:92
load (async)
_ajaxRequest @ Form.js?1592912073:81
(anonymous) @ Form.js?1592912073:30
Anything wrong with my extension settings? I run Typo3 9.5.19 with PHP 7.3

**Comment by rr-it** [comment]
Your TYPO3-instance might have a [Routing](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Routing/Introduction.html) configuration for page type.

E.g. for configured `routeEnhancers` --> `PageTypeSuffix` add the type `6171240` to your Routing:

``` yaml
routeEnhancers:
  PageTypeSuffix:
    map:
      'nlregistration.json': 6171240
```

**Comment by topsnet-holgerd** [comment]
I think, thats's the solution, thanks a lot. The lack in the extension manual related to this topic should perhaps be closed by you. Subsequently this issue can be closed as well.
