### ISSUE TITLE
Allow to use tt_address instead of fe_user for newsletter subscription.

### ISSUE THREAD

**Issue by extcode** [pixelant/pxa_newsletter_subscription#9]
We (TRITUM GmbH) use your extension for our newsletter subscription. Some new conditions will let us switch to tt_address instead of fe_user.

Our idea is to contribute some code to your extension to add a switch in the extension manager configuration to optional change the repository from fe_user to tt_address. Are you interested in this change or should we fork the extension for our own an change the repository directly for our projects?

**Comment by MattiasNilsson** [comment]
@extcode That sounds like an awesome idea! We would really like to have this as a PR :)

**Comment by BastianBalthasarBux** [comment]
Any news on that? Would be a really great enhancement!

**Comment by extcode** [comment]
Yes. I have to do some cleanup and documentation.

**Comment by tritum** [comment]
Why did extcode close this issue? We have developed the feature. I will take a look and will try to push a PR. Stay tuned.

**Comment by tritum** [comment]
Can you please re-open this issue?

**Comment by anjeylink** [comment]
@tritum done

**Comment by tritum** [comment]
https://github.com/pixelant/pxa_newsletter_subscription/pull/16
